urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'causknow'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('upload/', views.upload, name='upload'),
    path('sparql/', views.SPARQLQuery, name='sparql'),
    path('results/', views.SPARQLQuery, name='results')
] 
urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

models.py
from django.db import models

class FCM(models.Model):
    fcm_file = models.FileField(upload_to='fcmfiles/%Y/%m/%d')

views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

# from django.http import HttpResponse

from django.views.generic import TemplateView
from django.core.files.storage import FileSystemStorage

from .utils.rdfLoader import FusekiRdfLoader
from .utils.sparql import sparqlQuery

class Home(TemplateView):
    template_name = 'causknow/home.html'

def upload(request):
    context = {}
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        FusekiClass = FusekiRdfLoader(name)
        context['fusekiResponse'] = FusekiClass.httpResponse()
        context['url'] = fs.url(name)
        
    return render(request, 'causknow/upload.html', context)

def SPARQLQuery(request):
    context = {}
    if request.method == 'POST':
        UserSparqlQuery = request.POST.get('usersparqlquery', None)
        SparqlUtils = sparqlQuery(UserSparqlQuery)
        context['sparqlResults'] = SparqlUtils.sparqlResults()  

        return render(request, 'causknow/results.html', context)
    else:
        return render(request, 'causknow/sparql.html')    

templates/causknow/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>{% block title %}causKnow{% endblock %}</title>
    <script src="{% static 'codemirror.js' %}"></script>
    <link rel="stylesheet" href="{% static 'codemirror.css' %}">
    <link rel="stylesheet" href="{% static 'theme/material.css' %}">
    <script src="{% static 'mode/sparql/sparql.js' %}"></script>
    <script src="{% static 'mode/turtle/turtle.js' %}"></script>
    <script type="text/javascript">
        window.onload = function () {
        var config, editor;

        config = {
            lineNumbers: true,
            mode: "turtle",
            theme: "material",
        };

        editor = CodeMirror.fromTextArea(document.getElementById("template-html"), config);

        }
    </script>
</head>

<body class="bg-light">
    <div class="nav-scroller bg-white shadow-sm">
        <nav class="nav nav-underline">
            <a class="navbar-brand nav-link active" href="{% url 'causknow:home' %}">causKnow</a>
            <a class="nav-link" href="{% url 'causknow:upload' %}">
                Add FCM Data
                <!-- <span class="badge badge-pill bg-light align-text-bottom">27</span> -->
            </a>
            <a class="nav-link" href="{% url 'causknow:sparql' %}">Context-aware Knowledge Retrieval</a>
        </nav>
    </div>
    <main role="main" class="container">
        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
            <img class="mr-3" src="/docs/4.2/assets/brand/bootstrap-outline.svg" alt="" width="48" height="48">
            <div class="lh-100">
                <h6 class="mb-0 text-white lh-100">causKnow</h6>
                <small>Falconio</small>
            </div>
        </div>
        
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            {% block content %}
            {% endblock %}
        </div>

    </main>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</body>

</html>

templates/causknow/home.html
{% extends 'causknow/base.html' %}

{% block content %}

    <h6 class="border-bottom border-gray pb-2 mb-0">What is causKnow after all?</h6>
    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect fill="#007bff" width="100%" height="100%"></rect><text fill="#007bff" dy=".3em" x="50%" y="50%">32x32</text></svg>
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">1.</strong>
        causKnow is a semantic web-based application deployed on a cloud architecture.
      </p>
    </div>

    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect fill="#007bff" width="100%" height="100%"></rect><text fill="#007bff" dy=".3em" x="50%" y="50%">32x32</text></svg>
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">2.</strong>
        Basically, causKnow lays its foundation over ontological engineering principles. It makes use of a multi-layered ontological formalism for context-aware dissemination of causal knowledge about a given phenomenon. Read this scientific publication to find more. (<a href="https://www.sciencedirect.com/science/article/pii/S1474034618301642">https://www.sciencedirect.com/science/article/pii/S1474034618301642</a>)      </p>
    </div>

    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect fill="#007bff" width="100%" height="100%"></rect><text fill="#007bff" dy=".3em" x="50%" y="50%">32x32</text></svg>
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">3.</strong>
        At its core, causKnow appreciates certain epistemological concerns around knowledge sharing and reuse; by adding a context-sensing power to its knowledge retrieval mechanism. End user can define contextual attributes of interest and query a graph-based database containing FCM-driven causal knowledge representations.    
      </p>
    </div>

    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect fill="#007bff" width="100%" height="100%"></rect><text fill="#007bff" dy=".3em" x="50%" y="50%">32x32</text></svg>
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">4.</strong>
        The current meta-model of causKnow’s knowledge representation and reasoning scheme supports the Fuzzy Cognitive Mapping approach. FCM, combining the principles of neuro-computing and Fuzzy logic, is an intuitive tool which exploits expert causal judgements for anticipation of future states of highly dynamic, distributed, and complex systems. 
      </p>
    </div>

    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect fill="#007bff" width="100%" height="100%"></rect><text fill="#007bff" dy=".3em" x="50%" y="50%">32x32</text></svg>
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">5.</strong>
        At the moment, causKnow allows for uploading FCM scenarios as ontological instances in various serializations such as RDF/XML, Turtle, N3, etc.
      </p>
    </div>

    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect fill="#007bff" width="100%" height="100%"></rect><text fill="#007bff" dy=".3em" x="50%" y="50%">32x32</text></svg>
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">6.</strong>
        We believe in open knowledge-sharing in action! Find causKnow’s Github repo here: <a href="http://github.com/falconio">Falconio</a>
      </p>
    </div>

{% endblock %}

templates/causknow/results.html
{% extends "causknow/base.html" %}

{% block content %}
    <h5>SPARQL Query Results:</h5>
    <table class="table">
    {% for result in sparqlResults.results.bindings %}
         <tr>
            {% for item, param in result.items %}
                <td> {{ item.value }} </td>
                <td> {{ param.value }} </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </table>
    <br>
    <a class="btn btn-primary" href="{% url 'causknow:sparql' %}" role="button">Query Again</a>
{% endblock content %}

templates/causknow/sparql.html
{% extends "causknow/base.html" %}

{% block content %}
    <h5> Context-aware knowledge retrieval <small class="text-muted">using SPARQL Query</small> </h5>

    <form action="{% url 'causknow:results' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Enter your SPARQL: </label>
            <div class="CodeMirror cm-s-default CodeMirror-wrap">
                <textarea class="form-control" id="template-html" rows="10" name="usersparqlquery"></textarea>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Submit</button>
    </form>
{% endblock %}

templates/causknow/upload.html
{% extends "causknow/base.html" %}

{% block content %}
    <h5>Add new FCM data in RDF format (RDF/XML, Turtle, N3)</h5>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="custom-file">
                <input type="file" name="document" class="custom-file-input" id="inputGroupFile02">
                <label class="custom-file-label" for="inputGroupFile02" aria-describedby="inputGroupFileAddon02">Browse your FCM data</label>
            </div>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="inputGroupFileAddon04">Upload</button>
            </div>
        </div>
        <!-- <input type="file" name="document">
        <button type="submit">Upload</button> -->
    </form>
    {% if url %}
    <p>FCM data file: <a href="{{ url }}">{{ url }}</a></p>
    {% endif %}
    {% if fusekiResponse %}
    <p>Jena Fuseki Response: {{ fusekiResponse }}</p>
    {% endif %}
{% endblock content %}